name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies (LLVM)
      run: sudo apt-get install llvm-10-dev clang-10
    - name: Set LLVMCONFIG
      run: echo "LLVMCONFIG=llvm-config-10" >> $GITHUB_ENV
    - name: Initialize submodules
      run: make submodule
    - name: Compile jive and jlm
      run: make jive-release jlm-release
    - name: Run unit and C tests
      run: make check
    - name: Add jlc to PATH
      run: echo '/home/runner/work/jlm/jlm/bin' >> $GITHUB_PATH
  polybench:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Clone polybench
      run: git clone https://github.com/phate/polybench-jlm.git
    - name: Compare polybench
      run: make -C polybench-jlm compare
